version: '2'
services:
  web:
    build: .
    image: registry.gitlab.com/tcmal/hackmap:latest
    ports:
      - "8000:8000" # web
      - "8001:8001" # websocket
    environment:
      MQTT_HOST: mqtt.hacklab
    volumes:
      - ./:/app
    restart: always
