# Generated by Django 5.1 on 2025-05-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labprinter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='color',
            field=models.CharField(default='black', max_length=20),
        ),
    ]
