# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("labdash", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="buttongroup",
            name="lighttext",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="button",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buttons",
                to="labdash.ButtonGroup",
            ),
        ),
    ]
