# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labdash", "0002_auto_20161209_2252"),
    ]

    operations = [
        migrations.AddField(
            model_name="button",
            name="priority",
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="button",
            name="icon",
            field=models.FileField(upload_to=""),
        ),
    ]
