# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labdash", "0004_auto_20161214_0152"),
    ]

    operations = [
        migrations.AddField(
            model_name="buttongroup",
            name="priority",
            field=models.IntegerField(default=50),
        ),
    ]
