# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labdash", "0005_buttongroup_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="retain",
            field=models.BooleanField(default=False),
        ),
    ]
