# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2024-08-20 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("labdash", "0006_action_retain"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("priority", models.IntegerField(default=50)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sliders",
                        to="labdash.ButtonGroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SliderAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                ("min", models.IntegerField(default=0)),
                ("max", models.IntegerField(default=255)),
                (
                    "slider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="labdash.Slider",
                    ),
                ),
            ],
        ),
    ]
