# Generated by Django 5.1 on 2024-12-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labdash', '0010_remove_slideraction_slider_alter_action_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttongroup',
            name='tile_width',
            field=models.IntegerField(default=1),
        ),
    ]
