# Generated by Django 5.1 on 2024-12-11 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labdash', '0011_alter_buttongroup_tile_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buttongroup',
            name='lighttext',
        ),
    ]
