# Generated by Django 5.1 on 2024-12-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labdash', '0012_remove_buttongroup_lighttext'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='href',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
