# Generated by Django 5.1 on 2024-12-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labdash', '0013_button_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='href',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
